name: GitHub Pages
on:
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - run: composer install --ignore-platform-reqs
      - run: npm ci
      - run: npx vite build -- --config 'vite.github-pages.config.ts'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/build
      - uses: actions/deploy-pages@v4
