name: GitHub Pages
on:
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - run: npm ci
      - run: php artisan export
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4
