name: GitHub Pages
on:
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - run: composer install --ignore-platform-reqs
      - run: npm ci
      - run: |
          cp .env.example .env &&
          sed -i "s#APP_URL=http://localhost#APP_URL=http://localhost:8000#g" .env
          sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=http://localhost:5173#g" .env
          php artisan key:generate
          php artisan storage:link
          php artisan serve &
          npm run dev &
      - run: php artisan export
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4
